version: "3.8"

services:
  app:
    image: mongo:5
    entrypoint: mongosh 
    command: [ 
      "mongodb://root:root@mongo:27020/foo?replicaSet=rs0",
      "--authenticationDatabase",
      "admin",
      "--eval",
      "rs.status()" 
    ]

  mongo:
    build:
      context: .
      args:
        MONGO_VERSION: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27020
      MONGO_COMMAND: "mongosh"
    ports:
      - "27020:27020"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "admin", "--port", "$$MONGO_REPLICA_PORT", "--eval", "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20
